# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "cryptd"
    "aesni_intel"
    "nvme"
    "rtsx_pci_sdmmc"
    "sd_mod"
    "thunderbolt"
    "usb_storage"
    "vmd"
    "xhci_pci"
  ];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/cafc8704-c41f-49fc-a7bf-a1fbe4baf03b";
      preLVM = false;
      bypassWorkqueues = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=root" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  # Nocow for qcow2 files
  fileSystems."/home/kenny/VirtualMachines" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home_kenny_VirtualMachines" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  # TODO: should use XDG home
  fileSystems."/home/kenny/.local/share/go/pkg" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home_kenny_go_pkg" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=nix" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  # Using rootless podman, but was:
  fileSystems."/var/lib/docker" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=var_lib_docker" "commit=60" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E032-D07D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/run/media/black" = {
    device = "/dev/disk/by-uuid/779defff-0c31-4144-9cc7-840a17f7bdb6";
    fsType = "btrfs";
    options = [
        "noauto"                       # do not mount on boot
        "nofail"
        "x-systemd.automount"          # mount when needed
        "x-systemd.device-timeout=1ms" # device should be plugged already—do not wait for it
        "x-systemd.idle-timout=5m"     # unmount after 5 min of inactivity
    ];
  };

  # TESTING
  fileSystems."/persist" = {
    device = "/dev/mapper/root";
    # TODO: set once in use
    # neededForBoot = true;
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "commit=60"
      "noatime"
      "user_subvol_rm_allowed"
    ];
  };

  swapDevices = [
    {
      device = "/dev/nvme0n1p3";
      randomEncryption.enable = true;
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.cpu.x86.msr.enable = true; # Required for powertop
}
