keys:
  - &admin_kenny CC7C9BE4F442A854E29DF25695981B9FE3FB7465
  - &host_an age1p8fsxr8jd8kplhz7jnutg3memm7vd4hc3mk6w9k3pfmqmat0dgdqeja62n
  - &host_dn age1tzakv84yjzf4zlw2hfrauj7e3p7vrct4j5xvmhuupgq98fhpmyfqvmdmq2
  - &host_ke age1zfjrfcpws67kt05vtjcgus2r3vm75gu2hxke3tqgw9aqh5xkuu2qs83q2s
  - &host_r1pro age1pckfd9rhqq0vw22yq685tnw2a67mme9ftr7zmrm3hrglpafghacqdn3565
  - &host_yoga age1da2yp3vd85556a0eh0t52fgdjkh0f4fayvjddwe90awmj3w2x3csh4pkw6

creation_rules:
  - path_regex: hosts/an/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_kenny
      age:
      - *host_an
  - path_regex: hosts/ke/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_kenny
      age:
      - *host_ke
  - path_regex: hosts/r1pro/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_kenny
      age:
      - *host_r1pro
  - path_regex: hosts/yoga/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_kenny
      age:
      - *host_yoga
