# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "cryptd"
    "aesni_intel"
    "nvme"
    "rtsx_pci_sdmmc"
    "sd_mod"
    "thunderbolt"
    "usb_storage"
    "vmd"
    "xhci_pci"
  ];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/cafc8704-c41f-49fc-a7bf-a1fbe4baf03b";
      preLVM = false;
    };
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=root" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home" "noatime" "user_subvol_rm_allowed"];
  };

  # Nocow for qcow2 files
  fileSystems."/home/kenny/VirtualMachines" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home_kenny_VirtualMachines" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/home/kenny/.local/share/go/pkg" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=home_kenny_go_pkg" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime" "user_subvol_rm_allowed"];
  };

  # Using rootless podman, but was:
  fileSystems."/var/lib/docker" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=var_lib_docker" "noatime" "user_subvol_rm_allowed"];
  };

  # Also using overlay tmpfs... but keep in case need more room
  fileSystems."/tmp" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=tmp" "noatime" "user_subvol_rm_allowed"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E032-D07D";
    fsType = "vfat";
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
