# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "usb_storage"
    "sd_mod"
    "nvme"
    "vmd"
    "thunderbolt"
    "rtsx_pci_sdmmc"
    "xhci_pci"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=root" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=home" "noatime" ];
  };

  # Nocow for qcow2 files
  fileSystems."/home/kenny/VirtualMachines" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=home_kenny_VirtualMachines" "noatime" ];
  };

  fileSystems."/home/kenny/.local/share/containers" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=home_kenny_.local_share_containers" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=nix" "noatime" ];
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=var_lib_docker" "noatime" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/11903e46-6df3-4135-a6fb-b5bf4cdbbf25";
    fsType = "btrfs";
    options = [ "subvol=tmp" "relatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E032-D07D";
    fsType = "vfat";
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
