# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zroot/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DBDC-FF45";
      fsType = "vfat";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/6c0f7199-6d46-4340-b2f0-d9607693b160";
      fsType = "ext4";
    };

  fileSystems."/mnt/silver" =
    { device = "/dev/disk/by-uuid/1a5da77a-2086-4ca8-8f36-836d956b7035";
      fsType = "btrfs";
      options = [ "subvolid=0" ];
    };

  fileSystems."/mnt/multimedia" =
    { device = "/dev/disk/by-uuid/1a5da77a-2086-4ca8-8f36-836d956b7035";
      fsType = "btrfs";
      options = [ "subvol=multimedia" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d32bc8af-e3e6-4779-b084-eddb41415b8a"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
