# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/19453858-b1c4-459d-a09c-6bc96df06442";
    fsType = "btrfs";
    options = ["subvol=nixos_root" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/19453858-b1c4-459d-a09c-6bc96df06442";
    fsType = "btrfs";
    options = ["subvol=home" "noatime"];
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/19453858-b1c4-459d-a09c-6bc96df06442";
    fsType = "btrfs";
    options = ["subvol=var_lib_docker" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/19453858-b1c4-459d-a09c-6bc96df06442";
    fsType = "btrfs";
    options = ["subvol=nixos_nix" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DBDC-FF45";
    fsType = "vfat";
  };

  fileSystems."/mnt/silver" = {
    device = "/dev/disk/by-uuid/1a5da77a-2086-4ca8-8f36-836d956b7035";
    fsType = "btrfs";
    options = ["subvolid=0"];
  };

  fileSystems."/mnt/multimedia" = {
    device = "/dev/disk/by-uuid/1a5da77a-2086-4ca8-8f36-836d956b7035";
    fsType = "btrfs";
    options = ["subvol=multimedia"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d32bc8af-e3e6-4779-b084-eddb41415b8a";}
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
